### ISSUE TITLE
Data product rubric development

### ISSUE THREAD

**Issue by joelostblom** [UBC-MDS/simpl_eeg_capstone#122]
Hey @YikiSu, @mgaroub @MattTPin and @sbabicki !

I have been working on developing a suggestion for the rubric of your project, please let me know what you think and we can discuss at the end of this week or next.

The background for this is that every capstone project is unique, so it doesn't make sense to apply a standard grading rubric to every project's data product. Instead, this year mentors will develop a specific grading rubric for each of their teams. This has the purpose of being transparent with what constitutes the data product, and how the teams will be graded.

At the end of capstone, you will submit three things:

1. Final report
2. Final data product
3. Teamwork document

The team-specific rubric discussed in this document relates to point (2) only, the data product. The final report and teamwork document will have their own rubrics defined by the capstone coordinator. The reasoning rubric is mainly referring to the appropriateness of your solution and if you have understood and met the partners need. This is my suggestion, let me know your thoughts on whether these weightings and rubrics seem suitable for your project and we can iterate on it together if needed.

- 45% Python package {accuracy:20,efficiency:10,reasoning:30,quality:20,viz:20}
- 25% Dashboard {accuracy:20,efficiency:10,reasoning:30,quality:20,viz:20}
- 20% Documentation {reasoning:85,writing:15}
    - This includes standalone documentation, docstrings, code comments, readme files, and anything else that is required for the capstone partner to setup, use, and maintain all parts of the project.
        - The standalone documentation should contain general information, specific code examples, and an API reference for your functions.
    - The template notebooks that you create as a skeleton for the partners use cases of the package will be graded under this section.
- 10% Clustering {accuracy:20,efficiency:10,reasoning:40,quality:20,viz:10}
    - Since this is a stretch goal, you will not be penalized if you have not solved the partners problem, as long as you clearly demonstrate the progress you have made and the approach you took is appropriate, so that the partner could continue this work and solve their problem in the future.

Most of the quality rubric points will be used for reproducibility aspects such as having working setup/make files & tests, and that everything runs as expected from start to finish on a fresh install. The exact tools for reproducibility depend on the type of product, but all data products should at a minimum include a GitHub/GitLab repository containing all code necessary to recreate and test the data product, as well as a list of all software and environment dependencies (names and versions) required to create and use the data product. It should also be very well documented so that it can be both used by the client and extended by other data scientists in the future.

In addition to what you already learned about creating documentation during MDS, you can [consider using private GH pages](https://pages.github.ubc.ca/MDS-2020-21/DSCI_591_capstone-proj_students/deliverables/2-final-presentation-report-data-product.html#data-product) to share your docs with the partner in a polished website without making it available to the public, e.g. via a Jupyter Book or similar.

**Comment by joelostblom** [comment]
Accepted as final rubric today in the meeting.

**Comment by sbabicki** [comment]
@joelostblom For "API reference for your functions" is it sufficient to print the help pages for functions that we showcase in our documentation (e.g. https://ubc-mds.github.io/simpl_eeg_capstone/connectivity.html#define-parameters)? Or are you looking for something more specific?

**Comment by joelostblom** [comment]
Yes that is sufficient. If you want to make it prettier [you can follow these steps ](https://github.com/executablebooks/jupyter-book/pull/1233/files#diff-e8df3ed7657c1a15c3f719fcaf77b703cf7a666039436a3de95a860a92d4777a), but consider that a low prio "nice to have".

**Comment by sbabicki** [comment]
Ooo, that sounds really cool. We will check it out.
