### ISSUE TITLE
Blank 0.00s time for 2D headmap

### ISSUE THREAD

**Issue by sbabicki** [UBC-MDS/simpl_eeg_capstone#202]
@YikiSu could you explain how you were able to fix the 3D one? Probably Matt will handle this, but I'm wondering if he can use a similar method.

**Comment by YikiSu** [comment]
@sbabicki @MattTPin Because I use dataframe in my function, I noticed `df = df.loc[(df[channel_names] != 0).all(axis=1)]` could remove the blank 0.00s. Not sure whether this will work for your functions.

**Comment by sbabicki** [comment]
We should see if there is a way to do this in the created epoch object that gets passed in instead. That way the individual functions don't need to handle it.
